// <auto-generated />
using System;
using ClubeRank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubeRank.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ClubeRankDbContext))]
    [Migration("20260406215749_InitialClubeRankApp")]
    partial class InitialClubeRankApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubeRank.Domain.Entities.Atleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Atletas", (string)null);
                });

            modelBuilder.Entity("ClubeRank.Domain.Entities.Confronto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtletaAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtletaBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AtletaAId");

                    b.HasIndex("AtletaBId");

                    b.HasIndex("TorneioId");

                    b.ToTable("Confrontos", (string)null);
                });

            modelBuilder.Entity("ClubeRank.Domain.Entities.HistoricoRanking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfrontoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("ConfrontoId");

                    b.ToTable("HistoricosRanking", (string)null);
                });

            modelBuilder.Entity("ClubeRank.Domain.Entities.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Organizacoes", (string)null);
                });

            modelBuilder.Entity("ClubeRank.Domain.Entities.Torneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Torneios", (string)null);
                });

            modelBuilder.Entity("TorneioAtleta", b =>
                {
                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtletaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TorneioId", "AtletaId");

                    b.HasIndex("AtletaId");

                    b.ToTable("TorneioAtletas", (string)null);
                });

            modelBuilder.Entity("ClubeRank.Domain.Entities.Atleta", b =>
                {
                    b.OwnsOne("ClubeRank.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AtletaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("EmailValor");

                            b1.HasKey("AtletaId");

                            b1.ToTable("Atletas");

                            b1.WithOwner()
                                .HasForeignKey("AtletaId");
                        });

                    b.OwnsOne("ClubeRank.Domain.ValueObjects.Pontuacao", "PontuacaoAtual", b1 =>
                        {
                            b1.Property<Guid>("AtletaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DataAtualizacao")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataAtualizacaoPontuacao");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoAtual");

                            b1.HasKey("AtletaId");

                            b1.ToTable("Atletas");

                            b1.WithOwner()
                                .HasForeignKey("AtletaId");
                        });

                    b.OwnsOne("ClubeRank.Domain.ValueObjects.NomeCompleto", "Nome", b1 =>
                        {
                            b1.Property<Guid>("AtletaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("PrimeiroNome")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PrimeiroNome");

                            b1.Property<string>("Sobrenome")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Sobrenome");

                            b1.HasKey("AtletaId");

                            b1.ToTable("Atletas");

                            b1.WithOwner()
                                .HasForeignKey("AtletaId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Nome")
                        .IsRequired();

                    b.Navigation("PontuacaoAtual")
                        .IsRequired();
                });

            modelBuilder.Entity("ClubeRank.Domain.Entities.Confronto", b =>
                {
                    b.HasOne("ClubeRank.Domain.Entities.Atleta", "AtletaA")
                        .WithMany()
                        .HasForeignKey("AtletaAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubeRank.Domain.Entities.Atleta", "AtletaB")
                        .WithMany()
                        .HasForeignKey("AtletaBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubeRank.Domain.Entities.Torneio", "Torneio")
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ClubeRank.Domain.ValueObjects.ResultadoConfronto", "Resultado", b1 =>
                        {
                            b1.Property<Guid>("ConfrontoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DataRegistro")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataRegistroResultado");

                            b1.Property<string>("JustificativaWO")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("JustificativaWO");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("TipoResultado");

                            b1.HasKey("ConfrontoId");

                            b1.ToTable("Confrontos");

                            b1.WithOwner()
                                .HasForeignKey("ConfrontoId");
                        });

                    b.Navigation("AtletaA");

                    b.Navigation("AtletaB");

                    b.Navigation("Resultado");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("ClubeRank.Domain.Entities.HistoricoRanking", b =>
                {
                    b.HasOne("ClubeRank.Domain.Entities.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClubeRank.Domain.Entities.Confronto", "Confronto")
                        .WithMany()
                        .HasForeignKey("ConfrontoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("ClubeRank.Domain.ValueObjects.Pontuacao", "PontuacaoAntes", b1 =>
                        {
                            b1.Property<Guid>("HistoricoRankingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DataAtualizacao")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataPontuacaoAntes");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoAntes");

                            b1.HasKey("HistoricoRankingId");

                            b1.ToTable("HistoricosRanking");

                            b1.WithOwner()
                                .HasForeignKey("HistoricoRankingId");
                        });

                    b.OwnsOne("ClubeRank.Domain.ValueObjects.Pontuacao", "PontuacaoDepois", b1 =>
                        {
                            b1.Property<Guid>("HistoricoRankingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DataAtualizacao")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataPontuacaoDepois");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoDepois");

                            b1.HasKey("HistoricoRankingId");

                            b1.ToTable("HistoricosRanking");

                            b1.WithOwner()
                                .HasForeignKey("HistoricoRankingId");
                        });

                    b.Navigation("Atleta");

                    b.Navigation("Confronto");

                    b.Navigation("PontuacaoAntes")
                        .IsRequired();

                    b.Navigation("PontuacaoDepois")
                        .IsRequired();
                });

            modelBuilder.Entity("ClubeRank.Domain.Entities.Organizacao", b =>
                {
                    b.OwnsOne("ClubeRank.Domain.Entities.ConfiguracaoOrganizacao", "Configuracao", b1 =>
                        {
                            b1.Property<Guid>("OrganizacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DiasDecaimento")
                                .HasColumnType("int")
                                .HasColumnName("DiasDecaimento");

                            b1.Property<int>("PontuacaoDecaimentoSemanal")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoDecaimentoSemanal");

                            b1.Property<int>("PontuacaoDerrota")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoDerrota");

                            b1.Property<int>("PontuacaoEmpate")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoEmpate");

                            b1.Property<int>("PontuacaoInicial")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoInicial");

                            b1.Property<int>("PontuacaoMaxima")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoMaxima");

                            b1.Property<int>("PontuacaoMinima")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoMinima");

                            b1.Property<int>("PontuacaoPisoDecaimento")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoPisoDecaimento");

                            b1.Property<int>("PontuacaoVitoria")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoVitoria");

                            b1.Property<int>("PontuacaoWO")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoWO");

                            b1.HasKey("OrganizacaoId");

                            b1.ToTable("Organizacoes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizacaoId");
                        });

                    b.OwnsOne("ClubeRank.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("OrganizacaoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Email");

                            b1.HasKey("OrganizacaoId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Organizacoes");

                            b1.WithOwner()
                                .HasForeignKey("OrganizacaoId");
                        });

                    b.Navigation("Configuracao")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("ClubeRank.Domain.Entities.Torneio", b =>
                {
                    b.OwnsOne("ClubeRank.Domain.Entities.ConfiguracaoTorneio", "Configuracao", b1 =>
                        {
                            b1.Property<Guid>("TorneioId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("PermiteEmpate")
                                .HasColumnType("bit")
                                .HasColumnName("PermiteEmpate");

                            b1.Property<int>("PontuacaoDerrota")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoDerrota");

                            b1.Property<int>("PontuacaoEmpate")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoEmpate");

                            b1.Property<int>("PontuacaoVitoria")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoVitoria");

                            b1.Property<int>("PontuacaoWO")
                                .HasColumnType("int")
                                .HasColumnName("PontuacaoWO");

                            b1.HasKey("TorneioId");

                            b1.ToTable("Torneios");

                            b1.WithOwner()
                                .HasForeignKey("TorneioId");
                        });

                    b.Navigation("Configuracao")
                        .IsRequired();
                });

            modelBuilder.Entity("TorneioAtleta", b =>
                {
                    b.HasOne("ClubeRank.Domain.Entities.Atleta", null)
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubeRank.Domain.Entities.Torneio", null)
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
